### ISSUE TITLE
python3 -m pip install syntheon, Wheel error

### ISSUE THREAD

**Issue by santismo** [gudgud96/syntheon#7]
On mac, tried running install with terminal and on jupyter.
Gets stuck at the wheel, please help.

`Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zk/40l2b_cx4c5cqb25g1dy7w940000gn/T/pip-build-env-xtpiuqrt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/zk/40l2b_cx4c5cqb25g1dy7w940000gn/T/pip-build-env-xtpiuqrt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/zk/40l2b_cx4c5cqb25g1dy7w940000gn/T/pip-build-env-xtpiuqrt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/zk/40l2b_cx4c5cqb25g1dy7w940000gn/T/pip-build-env-xtpiuqrt/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
bash-3.2$ `

**Comment by santismo** [comment]
im kinda a newb...

is it just that i have to "python3 -m pip install" for all the requirements first?

librosa==0.9.1
torch==1.12.1
torchvision==0.13.1
torchaudio==0.12.1
pyyaml
mido 
nnAudio==0.3.1 
numpy 
bitstruct 
torchcrepeV2

**Comment by santismo** [comment]
got most the reqs working, except for these:

Requirement already satisfied: torch in ./anaconda3/lib/python3.11/site-packages (from syntheon) (2.1.0)
ERROR: Cannot install syntheon==0.0.1, syntheon==0.0.2 and syntheon==0.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    syntheon 0.1.0 depends on torch==1.12.1
    syntheon 0.0.2 depends on torch==1.12.1
    syntheon 0.0.1 depends on torchaudio==0.12.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by santismo** [comment]
Also am trying to share your work with the Vital community:
https://forum.vital.audio/t/has-anyone-tried-syntheon-for-vital-synplant-ai-for-vital/13617

**Comment by santismo** [comment]
Got it working, not sure how! Thank for your work!

**Comment by gudgud96** [comment]
Hi @santismo, glad it worked for you. Seems to me like an environmental issue as I did not encounter it while installing on Mac. Kindly re-open the issue if you face it again.
